# Generated by Django 3.1.2 on 2020-10-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='idGenero',
            new_name='Genero',
        ),
    ]
